services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - https://uptime-kuma-2nh4fq.fly.dev:3001/
      - 3001:3001
    restart: unless-stopped
